openapi: 3.0.0
info:
  title: GCP
  version: 1.0.0
servers:
  - url: https://iam.googleapis.com
security:
  - bearerAuth: [ ]
paths:
  /v1/projects/{projectId}/serviceAccounts:
    get:
      operationId: listServiceAccounts
      tags:
        - default
      summary: List Service Accounts
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    post:
      operationId: createServiceAccount
      tags:
        - default
      summary: Create Service Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                serviceAccount:
                  type: object
                  properties:
                    description:
                      type: string
                    displayName:
                      type: string
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccount'

  /v1/projects/{projectId}/serviceAccounts/{serviceAccountId}:
    get:
      operationId: getServiceAccount
      tags:
        - default
      summary: Get Service Account
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: serviceAccountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccount'
    patch:
      operationId: updateServiceAccount
      tags:
        - default
      summary: Update Service Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                updateMask:
                  type: string
                serviceAccount:
                  type: object
                  properties:
                    description:
                      type: string
                    displayName:
                      type: string
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: serviceAccountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccount'
    delete:
      operationId: deleteServiceAccount
      tags:
        - default
      summary: Delete Service Account
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: serviceAccountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ServiceAccount:
      type: object
      properties:
        name:
          type: string
        projectId:
          type: string
        uniqueId:
          type: string
        email:
          type: string
        etag:
          type: string
        oauth2ClientId:
          type: string
        displayName:
          type: string
        description:
          type: string