openapi: 3.0.0
info:
  title: GCP Compute Instance
  version: 1.0.0
servers:
  - url: https://compute.googleapis.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ComputeInstance:
      type: object
      properties:
        name:
          type: string
        machineType:
          type: string
        kind:
          type: string
        status:
          type: string
        zone:
          type: string
        fingerprint:
          type: string
security:
  - bearerAuth: [ ]
paths:
  /compute/v1/projects/{projectId}/zones/{zone}/instances:
    get:
      operationId: listComputeInstances
      tags:
        - default
      summary: List Instances
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: zone
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    post:
      operationId: createComputeInstance
      tags:
        - default
      summary: Create Instance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                machineType:
                  type: string
                serviceAccounts:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                disks:
                  type: array
                  items:
                    type: object
                    properties:
                      boot:
                        type: boolean
                      autoDelete:
                        type: boolean
                      diskSizeGb:
                        type: string
                      initializeParams:
                        type: object
                        properties:
                          diskName:
                            type: string
                          sourceImage:
                            type: string
                          diskSizeGb:
                            type: string
                networkInterfaces:
                  type: array
                  items:
                    type: object
                    properties:
                      networkTier:
                        type: string
                      subnetwork:
                        type: string
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: zone
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComputeInstance"
  /compute/v1/projects/{projectId}/zones/{zone}/instances/{name}:
    get:
      operationId: getComputeInstance
      tags:
        - default
      summary: Get Instance
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: zone
          in: path
          schema:
            type: string
          required: true
        - name: name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComputeInstance"
    put:
      operationId: updateComputeInstance
      tags:
        - default
      summary: Update Instance
      requestBody:
        content:
          '*/*':
            schema:
              type: string
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: zone
          in: path
          schema:
            type: string
          required: true
        - name: name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    delete:
      operationId: deleteComputeInstance
      tags:
        - default
      summary: Delete Instance
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
          required: true
        - name: zone
          in: path
          schema:
            type: string
          required: true
        - name: name
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  id:
                    type: string
                  kind:
                    type: string
                  status:
                    type: string
                  zone:
                    type: string
                  operationType:
                    type: string